"""Optional adapters for external state-space projects."""

from bayesfilter.adapters.bgs import (
    BGSConstrainedLikelihoodResult,
    BGSPosteriorAdapter,
    BGSPosteriorComponents,
    constrained_log_prior_and_score,
    log_abs_det_jacobian as bgs_log_abs_det_jacobian,
    theta_from_unconstrained as bgs_theta_from_unconstrained,
    unconstrained_from_theta as bgs_unconstrained_from_theta,
)
from bayesfilter.adapters.dsge import (
    DSGEStructuralAdapterGateResult,
    dsge_structural_adapter_gate,
)
from bayesfilter.adapters.macrofinance import (
    DerivativeCoverageMetadata,
    FiniteDifferenceOracleMetadata,
    IdentificationEvidenceMetadata,
    CrossCurrencyDerivativeGateResult,
    LargeScaleAdaptationGateResult,
    MacroFinanceHMCBackendComparisonResult,
    MacroFinanceHMCDiagnosticGateResult,
    MacroFinanceDerivativeResult,
    MacroFinanceHMCGateResult,
    MacroFinanceHMCReadinessResult,
    MacroFinanceLikelihoodResult,
    ObservationMaskMetadata,
    ParameterUnitMetadata,
    ReadinessBlockerMetadata,
    ProductionExposureGateResult,
    SparseBackendPolicyMetadata,
    compare_macrofinance_hmc_backend_diagnostics,
    evaluate_cross_currency_derivative_gate,
    evaluate_large_scale_adaptation_gate,
    evaluate_macrofinance_hmc_diagnostic_gate,
    evaluate_macrofinance_hmc_gate,
    evaluate_macrofinance_hmc_readiness,
    evaluate_macrofinance_provider_derivatives,
    evaluate_macrofinance_provider_likelihood,
    evaluate_production_exposure_gate,
    extract_derivative_coverage_metadata,
    extract_finite_difference_oracle_metadata,
    extract_identification_evidence_metadata,
    extract_observation_mask_metadata,
    extract_parameter_unit_metadata,
    extract_readiness_blocker_metadata,
    extract_sparse_backend_policy_metadata,
    macrofinance_lgssm_to_bayesfilter,
)

__all__ = [
    "BGSConstrainedLikelihoodResult",
    "BGSPosteriorAdapter",
    "BGSPosteriorComponents",
    "DerivativeCoverageMetadata",
    "DSGEStructuralAdapterGateResult",
    "FiniteDifferenceOracleMetadata",
    "IdentificationEvidenceMetadata",
    "CrossCurrencyDerivativeGateResult",
    "LargeScaleAdaptationGateResult",
    "MacroFinanceHMCBackendComparisonResult",
    "MacroFinanceHMCDiagnosticGateResult",
    "MacroFinanceDerivativeResult",
    "MacroFinanceHMCGateResult",
    "MacroFinanceHMCReadinessResult",
    "MacroFinanceLikelihoodResult",
    "ObservationMaskMetadata",
    "ParameterUnitMetadata",
    "ReadinessBlockerMetadata",
    "ProductionExposureGateResult",
    "SparseBackendPolicyMetadata",
    "compare_macrofinance_hmc_backend_diagnostics",
    "dsge_structural_adapter_gate",
    "evaluate_cross_currency_derivative_gate",
    "evaluate_large_scale_adaptation_gate",
    "evaluate_macrofinance_hmc_diagnostic_gate",
    "evaluate_macrofinance_hmc_gate",
    "evaluate_macrofinance_hmc_readiness",
    "evaluate_macrofinance_provider_derivatives",
    "evaluate_macrofinance_provider_likelihood",
    "evaluate_production_exposure_gate",
    "extract_derivative_coverage_metadata",
    "extract_finite_difference_oracle_metadata",
    "extract_identification_evidence_metadata",
    "extract_observation_mask_metadata",
    "extract_parameter_unit_metadata",
    "extract_readiness_blocker_metadata",
    "extract_sparse_backend_policy_metadata",
    "macrofinance_lgssm_to_bayesfilter",
    "constrained_log_prior_and_score",
    "bgs_log_abs_det_jacobian",
    "bgs_theta_from_unconstrained",
    "bgs_unconstrained_from_theta",
]
