"""Optional adapters for external state-space projects."""

from bayesfilter.adapters.macrofinance import (
    DerivativeCoverageMetadata,
    FiniteDifferenceOracleMetadata,
    IdentificationEvidenceMetadata,
    MacroFinanceDerivativeResult,
    MacroFinanceHMCGateResult,
    MacroFinanceHMCReadinessResult,
    MacroFinanceLikelihoodResult,
    ObservationMaskMetadata,
    ParameterUnitMetadata,
    ReadinessBlockerMetadata,
    SparseBackendPolicyMetadata,
    evaluate_macrofinance_hmc_gate,
    evaluate_macrofinance_hmc_readiness,
    evaluate_macrofinance_provider_derivatives,
    evaluate_macrofinance_provider_likelihood,
    extract_derivative_coverage_metadata,
    extract_finite_difference_oracle_metadata,
    extract_identification_evidence_metadata,
    extract_observation_mask_metadata,
    extract_parameter_unit_metadata,
    extract_readiness_blocker_metadata,
    extract_sparse_backend_policy_metadata,
    macrofinance_lgssm_to_bayesfilter,
)

__all__ = [
    "DerivativeCoverageMetadata",
    "FiniteDifferenceOracleMetadata",
    "IdentificationEvidenceMetadata",
    "MacroFinanceDerivativeResult",
    "MacroFinanceHMCGateResult",
    "MacroFinanceHMCReadinessResult",
    "MacroFinanceLikelihoodResult",
    "ObservationMaskMetadata",
    "ParameterUnitMetadata",
    "ReadinessBlockerMetadata",
    "SparseBackendPolicyMetadata",
    "evaluate_macrofinance_hmc_gate",
    "evaluate_macrofinance_hmc_readiness",
    "evaluate_macrofinance_provider_derivatives",
    "evaluate_macrofinance_provider_likelihood",
    "extract_derivative_coverage_metadata",
    "extract_finite_difference_oracle_metadata",
    "extract_identification_evidence_metadata",
    "extract_observation_mask_metadata",
    "extract_parameter_unit_metadata",
    "extract_readiness_blocker_metadata",
    "extract_sparse_backend_policy_metadata",
    "macrofinance_lgssm_to_bayesfilter",
]
