"""Render checked HMC tuning interface tables from the capability registry."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bayesfilter.inference.tuning_contract import (
    HMC_TUNING_CAPABILITY_REGISTRY_SCHEMA,
    HMC_TUNING_INTERFACE_CAPABILITIES,
    HMCTuningInterfaceCapability,
    hmc_tuning_capability_registry_payload,
)


OUTPUT_PATHS = (
    Path("docs/generated/hmc_tuning_route_table.md"),
    Path("docs/generated/hmc_tuning_route_table.tex"),
)


def _markdown_text(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _tex_text(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def _tex_status(value: object) -> str:
    return _tex_text(str(value).replace("_", " "))


def _joined(values: Iterable[str]) -> str:
    return "; ".join(str(value) for value in values)


def render_markdown(
    records: Iterable[HMCTuningInterfaceCapability] = HMC_TUNING_INTERFACE_CAPABILITIES,
) -> str:
    rows = tuple(records)
    lines = [
        "<!-- Generated by scripts/render_hmc_tuning_interface_docs.py. Do not edit. -->",
        "",
        "# HMC Tuning Interface Capabilities",
        "",
        f"Registry schema: `{HMC_TUNING_CAPABILITY_REGISTRY_SCHEMA}`.",
        "",
        "| Interface | Kind / status | Authority | Target and coordinates | Mass / epsilon / L | Fresh verification and ESS | Injection or replacement |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for record in rows:
        lines.append(
            "| "
            + " | ".join(
                _markdown_text(value)
                for value in (
                    f"`{record.qualified_name}`",
                    f"{record.interface_kind}; {record.capability_status}",
                    "canonical artifact authority"
                    if record.artifact_authority
                    else "no artifact authority",
                    (
                        f"{record.target_contract}; coordinates: "
                        f"{record.coordinate_prerequisite}"
                    ),
                    (
                        f"mass: {record.mass_policy}; epsilon: "
                        f"{record.step_size_policy}; L: {record.trajectory_policy}"
                    ),
                    (
                        f"verification: {record.fresh_verification_policy}; ESS: "
                        f"{record.ess_admission_policy}"
                    ),
                    record.runner_injection_policy
                    if record.replacement is None
                    else f"replacement: `{record.replacement}`; {record.runner_injection_policy}",
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Identity, Restrictions, And Evidence",
            "",
        ]
    )
    for record in rows:
        lines.extend(
            [
                f"### `{record.qualified_name}`",
                "",
                f"- Target-status evidence: {_markdown_text(record.target_status_telemetry)}.",
                f"- Bound identity: {_markdown_text(_joined(record.identity_bindings))}.",
                f"- Source closure: {_markdown_text(record.source_closure_policy)}.",
                f"- Forbidden uses: {_markdown_text(_joined(record.forbidden_uses))}.",
                f"- Nonclaims: {_markdown_text(_joined(record.nonclaims))}.",
                f"- Evidence anchors: {_markdown_text(_joined(record.evidence_anchors))}.",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_tex(
    records: Iterable[HMCTuningInterfaceCapability] = HMC_TUNING_INTERFACE_CAPABILITIES,
) -> str:
    rows = tuple(records)
    lines = [
        "% Generated by scripts/render_hmc_tuning_interface_docs.py. Do not edit.",
        r"\begingroup",
        r"\footnotesize",
        r"\sloppy",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.26\textwidth}>{\raggedright\arraybackslash}p{0.14\textwidth}>{\raggedright\arraybackslash}p{0.53\textwidth}}",
        r"\toprule",
        r"Interface & Status & Target, tuning, verification, and use \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Interface & Status & Target, tuning, verification, and use \\",
        r"\midrule",
        r"\endhead",
    ]
    for record in rows:
        status = (
            f"{record.interface_kind}; {record.capability_status}; "
            + ("authority" if record.artifact_authority else "no authority")
        )
        details = (
            f"Target: {record.target_contract}. Coordinates: "
            f"{record.coordinate_prerequisite}. Mass: {record.mass_policy}. "
            f"Epsilon: {record.step_size_policy}. L: {record.trajectory_policy}. "
            f"Verification: {record.fresh_verification_policy}. "
            f"ESS: {record.ess_admission_policy}. "
            f"Forbidden: {_joined(record.forbidden_uses)}."
        )
        if record.replacement is not None:
            details += f" Replacement: {record.replacement}."
        lines.append(
            r"\path{" + record.qualified_name + "}"
            + " & "
            + _tex_status(status)
            + " & "
            + _tex_text(details)
            + r" \\"
        )
        lines.append(r"\addlinespace")
    lines.extend([r"\bottomrule", r"\end{longtable}", r"\endgroup"])
    return "\n".join(lines) + "\n"


def expected_outputs() -> Mapping[Path, str]:
    hmc_tuning_capability_registry_payload()
    return {
        OUTPUT_PATHS[0]: render_markdown(),
        OUTPUT_PATHS[1]: render_tex(),
    }


def write_or_check(repo_root: Path, *, check: bool) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in expected_outputs().items():
        path = repo_root / relative_path
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(relative_path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    return tuple(stale)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = write_or_check(args.repo_root.resolve(), check=args.check)
    if stale:
        for path in stale:
            print(f"stale generated HMC tuning documentation: {path}", file=sys.stderr)
        return 1
    if not args.check:
        for path in OUTPUT_PATHS:
            print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
