"""Render observed validation coverage; no numerical or sampler execution."""
from __future__ import annotations

import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path


def render(reports, markdown, latex):
    repo=Path(__file__).resolve().parents[1]
    files={str(p.relative_to(repo)):hashlib.sha256(p.read_bytes()).hexdigest()
           for p in sorted((repo/"bayesfilter").rglob("*.py"))}
    current_identity=hashlib.sha256(json.dumps(files,sort_keys=True,separators=(",", ":")).encode()).hexdigest()
    groups=defaultdict(lambda:{"current":0,"historical":0,"assessed":0,"planned":0,"findings":set()})
    sources=[]
    for path in reports:
        payload=json.loads(path.read_text())
        if payload["schema"]!="bayesfilter.inference_validation_report.v1":
            raise ValueError("unsupported coverage report")
        sources.append(str(path))
        index_path=path.parent/"run_index.json"
        source_identity=(json.loads(index_path.read_text())["source"]["identity"]
                         if index_path.exists() else None)
        for row in payload["rows"]:
            if row["control"]!="baseline":
                continue  # Mutation findings have their own report, not baseline coverage.
            key=(row["target"],row["route"],row.get("transport","none"),row["device"],row["engine"])
            group=groups[key]
            group["planned"]+=1
            executed=row["execution_status"]=="complete"
            current=executed and source_identity==current_identity
            group["current"]+=int(current)
            group["historical"]+=int(executed and not current)
            group["assessed"]+=int(current and row.get("assessment_complete",False))
            group["findings"].add(row["finding"] or row["execution_status"])
    md=["<!-- Generated by scripts/render_inference_validation_coverage.py -->",
        "| Target | Route / device | Question | Current / historical / planned | Current complete assessments | Findings |",
        "| --- | --- | --- | ---: | ---: | --- |"]
    tex=[r"% Generated by scripts/render_inference_validation_coverage.py",
         r"\begingroup\small\setlength{\tabcolsep}{3pt}",
         r"\begin{longtable}{>{\raggedright\arraybackslash}p{.15\textwidth}>{\raggedright\arraybackslash}p{.19\textwidth}>{\raggedright\arraybackslash}p{.13\textwidth}>{\raggedright\arraybackslash}p{.14\textwidth}>{\raggedright\arraybackslash}p{.28\textwidth}}",
         r"Target & Route/device & Question & C / H / P & Findings \\\hline\endhead"]
    def esc(value):
        return value.replace("_"," ")
    targets={"normal_conjugate":"Normal-normal", "beta_binomial":"Beta-binomial",
             "lgssm_location":"LGSSM location", "student_t":"Student t", "eight_schools":"Eight schools"}
    routes={"ordinary":"Automatic", "prepared":"Prepared", "fixed_transport":"Transport",
            "frozen":"Frozen kernel", "controller":"Controller", "external":"External", "reference":"Reference"}
    for (target,route,transport,device,engine),group in sorted(groups.items()):
        count=f"{group['current']} / {group['historical']} / {group['planned']}"
        findings=", ".join(sorted(group["findings"]))
        target=targets.get(target,target.capitalize())
        route=({"bayesfilter.neutra.frozen_affine_diag.v1":"Affine transport",
                "bayesfilter.neutra.dense_iaf_frozen_transport.v1":"Dense IAF"}.get(transport,routes[route])
               +" / "+("GPU" if device=="gpu" else "CPU"))
        engine="SBC" if engine=="sbc" else engine.capitalize()
        findings=esc(findings)
        md.append(f"| {target} | {route} | {engine} | {count} | {group['assessed']} | {findings} |")
        tex.append(" & ".join(map(esc,(target,route,engine,count,findings)))+r" \\")
    tex.extend([r"\end{longtable}",r"\endgroup",""])
    md.extend(["","C / H / P denotes current-checkout source executions / historical or unverified-source executions / planned designs (including retries). Source status is recomputed when this table is rendered; matching an old frozen snapshot does not imply matching the current checkout. Counts are not validated models or independent replications. Complete assessment additionally requires usable posterior output where applicable; it does not imply a passing result. Findings retain incomplete calibration and unavailable references.","",
               *[f"Source: `{p}`" for p in sources],""])
    markdown.parent.mkdir(parents=True,exist_ok=True)
    latex.parent.mkdir(parents=True,exist_ok=True)
    markdown.write_text("\n".join(md))
    latex.write_text("\n".join(tex))


if __name__=="__main__":
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("reports",type=Path,nargs="+")
    parser.add_argument("--markdown",type=Path,default=Path("docs/generated/inference_validation_coverage.md"))
    parser.add_argument("--latex",type=Path,default=Path("docs/generated/inference_validation_coverage.tex"))
    args=parser.parse_args()
    render(args.reports,args.markdown,args.latex)
