from __future__ import annotations

import json
from pathlib import Path

import pytest

from docs.benchmarks import run_cubature_exact_sv_score_ladder as score_ladder
from docs.benchmarks import run_cubature_genut_exact_sv_claim_diagnostic as claim
from docs.benchmarks import run_cubature_genut_exact_sv_n_scaling as scaling
from docs.benchmarks import run_exact_sv_fixed_gaussian_genut_paired as paired


ROOT = Path(__file__).resolve().parents[2]
CORRECTION = (
    ROOT
    / "docs/plans/bayesfilter-exact-sv-nondgp-fixture-demotion-correction-2026-07-22.md"
)


@pytest.mark.parametrize(
    "call",
    [
        lambda path: claim.run(path),
        lambda path: scaling.run(path),
        lambda path: score_ladder.run(path),
    ],
)
def test_revoked_nondgp_runners_fail_before_execution(tmp_path: Path, call) -> None:
    output = tmp_path / "must_not_exist"
    with pytest.raises(RuntimeError, match="revoked non-DGP fixture"):
        call(output)
    assert not output.exists()


def test_active_paired_runner_defaults_to_dgp_only() -> None:
    source = (
        ROOT / "docs/benchmarks/run_exact_sv_fixed_gaussian_genut_paired.py"
    ).read_text(encoding="utf-8")
    assert 'observations = {"fresh_dgp": fresh}' in source
    assert "include_historical_nondgp_engineering_only: bool = False" in source
    assert 'eligible_datasets = ("fresh_dgp",)' in source


@pytest.mark.parametrize(
    "relative_path",
    [
        "docs/plans/bayesfilter-cubature-genut-model-claim-plan-2026-07-21.md",
        "docs/plans/bayesfilter-cubature-genut-model-claim-phase3-result-2026-07-21.md",
        "docs/plans/bayesfilter-cubature-genut-exact-sv-n1000-plan-2026-07-21.md",
        "docs/plans/bayesfilter-cubature-genut-exact-sv-n1000-result-2026-07-21.md",
        "docs/plans/bayesfilter-exact-sv-cubature-score-bias-variance-ladder-plan-2026-07-21.md",
        "docs/plans/bayesfilter-exact-sv-cubature-score-bias-variance-ladder-result-2026-07-21.md",
    ],
)
def test_affected_scientific_documents_have_revocation_banner(
    relative_path: str,
) -> None:
    text = (ROOT / relative_path).read_text(encoding="utf-8")
    assert "HISTORICAL_NONDGP_ENGINEERING_ONLY" in text
    assert "Correction, 2026-07-22" in text
    assert "revoked" in text.lower()


def test_correction_artifact_excludes_original_dataset() -> None:
    payload = json.loads(
        (
            ROOT
            / "docs/benchmarks/artifacts/"
            "exact_sv_fixed_gaussian_genut_paired_20260721/"
            "correction_20260722.json"
        ).read_text(encoding="utf-8")
    )
    assert payload["scientifically_eligible_dataset_keys"] == ["fresh_dgp"]
    assert set(payload["scientifically_ineligible_dataset_keys"]) == {"original"}
    assert payload["revoked_source_field"] == "mechanism_support"
    assert CORRECTION.exists()


@pytest.mark.parametrize(
    "relative_path",
    [
        "docs/benchmarks/artifacts/cubature_genut_model_claim_20260721/REVOCATION.md",
        "docs/benchmarks/artifacts/cubature_genut_exact_sv_n1000_20260721/REVOCATION.md",
        "docs/benchmarks/artifacts/cubature_exact_sv_score_ladder_20260721/REVOCATION.md",
    ],
)
def test_affected_artifact_roots_have_revocation_sidecars(relative_path: str) -> None:
    text = (ROOT / relative_path).read_text(encoding="utf-8")
    assert "Revoked As SV Scientific Evidence" in text
    normalized = " ".join(text.split())
    assert "not generated by the declared stochastic-volatility DGP" in normalized
